version: '3'

services:
    library_db:
        image: postgres
        container_name: library_db
        ports:
            ["5432:5432"]
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
    back:
        build: 
            context: ./library_back
            dockerfile: Dockerfile 
        command: python manage.py runserver 0.0.0.0:8080
        image: my-back
        container_name: my-back
        ports:
            ["8080:8080"]
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        depends_on:
            - library_db
