version: '3'

services:
    library_db:
        image: postgres
        container_name: library_db
        ports:
            ["0000:5432"]
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password

    back:
        image: my-back
        container_name: back
        ports:
            ["8080:8080"]

    front:
        image: my-front
        container_name: front
        ports:
            ["3000:3000"]