version: '3'

services:
    library_db:
        image: postgres
        ports:
            ["5432:5432"]
        environment:
            - POSTGRES_PASSWORD=password
    aplicacao:
        image: my-app
        ports:
            ["8080:8080"]
        